- main.tf
- templates/fluentd-es.yaml.tpl
- Always is good to have a Chart version pinned, so not always is pinned the latest.
- Added tolerations values to the fluentd helm chart
> Set values of tolerations and chart version

- main.tf
More information here: https://github.com/ministryofjustice/cloud-platform-helm-charts/pull/9/files
> Upgrade the chart in order to make it Helm 3 compatible

- main.tf
- resources/filter-kubernetes.config
- resources/input-kubernetes.config
- resources/output-elasticsearch.config
- resources/parsers.config
Reduced the amount of configuration and fixed the path for the input in nginx side
> Second iteration - improved configuration

- variables.tf
Enabled fluent-bit **by default**
> Enable fluent-bit by default

- main.tf
change ns annotations for monitoring the namespace
> Change NS annotations for logging

- main.tf
It is causing divergence to fail
> Update stable helm repo to new URL

- main.tf
- templates/fluent-bit.yaml.tpl
- variables.tf
- New variable to let the module known where it is (EKS or KOPS)
- Updated module to the latest (minor release) 
- Set repository as a value conditional (in EKS points to ECR and in KOPS points to default)
> update fluent bit custom repo eks

- resources/output-elasticsearch.config
retries are staggered, will wait in total >30 mins
> max 5 tries to flush

- templates/fluent-bit.yaml.tpl
This is fix this warning:"failed to flush chunk"
> Set Merge_Log Off for kubernetes logs

- README.md
- variables.tf
Update the module to remove any references to live-1 and EKS
> Live-1 clean-up logging module

- templates/fluent-bit.yaml.tpl
This includes new v1 ingress controllers(default and modsec)
> Single index for ingress controller logs

- templates/fluent-bit.yaml.tpl
This is to make it shorter fits with in the search
> Update Logstash_Prefix for kubernetes and ingress

- README.md
- main.tf
Needs to go, replaced by an Index State management policy (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ism.html)
> delete curator job

- examples/logging.tf
- main.tf
- versions.tf
This PR:
- runs terraform fmt
- adds minimum provider versions
> Refactor to meet standardised Terraform structure

- .github/workflows/push-terraform-module-version.yaml
- README.md
Programatically add a new gh action that will post new releases/ versions to our API
> Add gh action to push new terraform module releases to our API

- main.tf
- templates/fluent-bit.yaml.tpl
containerd
View fixed logs https://eu-west-2.console.aws.amazon.com/aos/home?region=eu-west-2#opensearch/domains/jas-fluentbit-test-2?tabId=securityConfig
> chore: 🤖 bumper fluent-bit version to latest and adjust cri regex for

- templates/fluent-bit.yaml.tpl
config set twice and alias causing output issues
> fix: 🐛 config error

- main.tf
https://mojdt.slack.com/archives/C8QR5FQRX/p1693812335751479
> perf: ⚡️ we are seeing a few oom killed, bump mem limit

- README.md
- main.tf
- templates/fluent-bit.yaml.tpl
- variables.tf
configure fluent bit to push user app logs to new opensearch
> feat: 🎸 push user app logs to opensearch in parallel

- README.md
- versions.tf
Relates to ministryofjustice/cloud-platform#5380
> switch from gavinbunney to alekc kubectl provider

- templates/fluent-bit.yaml.tpl
refactor: 💡 lua split on "_" and reformat into an array of strings
The [label-pods webhook reads the github teams from rbac and then adds the teams to the pod label.](https://github.com/ministryofjustice/cloud-platform-label-pods/pull/18) Fluent bit runs the lua over the label and splits it into an array. For backwards compatibility (pods which came up before the label pods webhooks has been turned on), if the label doesn't exist then "all-org-members" is given as the default team.
eg. with the below log any user who is in either of the stated teams will be able to view the log
> style: 💄 reformat github_teams for fgac

- main.tf
relates to ministryofjustice/cloud-platform#5449
> bump fluent-bit to 3.0.2

- templates/fluent-bit.yaml.tpl
disabling fluentbit forwarding of app-logs to opensearch whilst investigating cluster node volume issues
> chore: 🤖 temp disabling of opensearch output, filter and lua

- main.tf
relates to ministryofjustice/cloud-platform#5994
> chore: 🤖 cleanup redundant KIAM annotations

- templates/fluent-bit.yaml.tpl
closes https://github.com/ministryofjustice/cloud-platform/issues/5690
> chore: 🤖 deprecate elasticsearch

- templates/fluent-bit.yaml.tpl
> Debug stdout

- templates/fluent-bit.yaml.tpl
- turn on flb debugging
- add json parser to nginx tail
- temporarily turn off event router
> fix: 🐛 wip debug timestamp issue

- main.tf
pick up filter fix https://github.com/fluent/fluent-bit/pull/8473
> chore: 🤖 bump to latest flb

- templates/fluent-bit.yaml.tpl
- get fluent bit logs back in open search
> feat: 🎸 turn on fluent bit app logs in os

- templates/fluent-bit.yaml.tpl
- we have a memory leak in flb pod
> fix: 🐛 add rety limit to fix potential memory leak
