main.tf

Part of our Helm3 upgrade requires setting up repository explicitly, otherwise we face [this issue](https://github.com/terraform-providers/terraform-provider-helm/issues/448).

Setting repository explicitly

---

README.md
main.tf
variables.tf

This cronjob runs every day to delete indices older than 30 days.
This job is maintained in [Environments repo](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live-1.cloud-platform.service.justice.gov.uk/logging/elasticsearch-curator.yaml), moved here to logging module.

Add elastic-search curator cronjob in logging

---

main.tf

To fix error, required key not provided @ data['timestring']
https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_age.html#_age_calculation

Updated source in curator cronjob to creation_date

---

main.tf

To use source as name and timestring,
this will delete the index older than 30 days with timestring "%Y.%m.%d"

Update elasticsearch-curator filter

---

main.tf

Fluentbit helm chart add ServiceMonitor and in order to do that it required Prometheus CRDs in place.

fluentbit depends on Prometheus

---

resources/input-kubernetes.config

This update the regular expression in order to match all ingress controllers pods within ìngress-controllers` namespace

Updated regex to match all ingress controllers pods

---

resources/filter-kubernetes.config
resources/input-kubernetes.config
resources/output-elasticsearch.config

This PR will add a seperate data pipeline in fluent-bit to parse eventrouter logs. It uses 'generic-json' parser, collect logs from path '/var/log/containers/eventrouter-*.log' and pushes to elasticsearch with prefix 'eventrouter'
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2252

Add additional config in fluent-bit to parse eventrouter logs as json

---

main.tf

As part of https://github.com/ministryofjustice/cloud-platform/issues/2369 we are setting up the network policies within the terraform module, so test clusters can also have them.

Added network policies

---

main.tf

The divergence pipeline is failing with:
```
~ spec {
~ limit {
~ default                 = {
~ "cpu"    = "1" -> "1000m"
"memory" = "1000Mi"
}
```

Updated LimitRange so k8s don't keep changing `1000m` -> `1`

---

main.tf

As we have fluent-bit and fluentd daemonsets running in logging namespace

Increase pod limit to 100 for logging namespace

---

main.tf

This chart has been moved to the cloud-platform helm chart. This commit
changes which chart we're pointing at.

Change helm repository for eventrouter

---

main.tf

An issue occurred whereby the cli version of elasticsearch_curator
doesn't run on python3.9. This wasn't captured and subsequently we ran
out of space in our Elasticsearch cluster. This commit pins the working
version of Python3 in the image.

Pin Python version in alpine image

---

main.tf

This is to fix the indices deletion error: No such command 'delete_indices', as curator_cli command is now updated to "delete-indices"

Update elasticsearch curator job

---

resources/output-elasticsearch.config

This will fix index issue, as kubernetes_cluster_live* also serves kubernetes_cluster_live-1*.
This change will have a cluster name at the front so it will fix the above issue.

Update prefix for index using cluster name

---

main.tf
resources/prometheusrule-alerts/alerts.yaml
versions.tf

- Add prometheus_rule_alert for fluent bit. This is to alert when "fluentbit_output_retries_failed_total" > 0
- Add ttl_seconds_after_finished for curator cronjob. This is to keep the job for 2 days, to get alert when failed, as clear completed jobs clean the jobs without ttl.

Fluent bit alert

---

main.tf
versions.tf

Add helm dependency for prometheus_rule_alert, as prometheus_rule_alert have a dependency for Prometheus, and fluent-bit helm deployment already got a dependency on Prometheus.

Add helm dependency for prometheus_rule_alert

---

resources/input-kubernetes.config

Noticed 
```
fluent-bit-9dwzv fluent-bit [2021/11/10 11:20:12] [error] [in_tail] file=/var/log/kube-apiserver-audit.log requires a larger buffer size, lines are too long. Skipping file.
```
in logs

bigger audit buffers

---

templates/fluent-bit.yaml.tpl

This is to fix the warning:
cannot increase buffer: current=32000 requested=64768 max=32000
This is fixed in release 1.8.7( https://github.com/fluent/fluent-bit/issues/3900), 
but we can't go to that version yet, as we have an open issue related to DNS (
https://github.com/fluent/fluent-bit/issues/4260)

Increased buffer size to 1MB, default is 32k

---

templates/fluent-bit.yaml.tpl

This is to avoid users having issues with thier dashboards

Revert Logstash_Prefix changes

---

main.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/4176
Include version when installing the helm chart. By default, helm installs the latest version for new clusters. But for existing clusters live, manager etc, it doesnot fetch the latest chart unless the version is specified.

Bump eventrouter chart to 0.3.3

---

.github/workflows/unit.yml
README.md
examples/logging.tf
main.tf
templates/fluent-bit.yaml.tpl
variables.tf

Related to: https://github.com/ministryofjustice/cloud-platform/issues/4439
This PR:
- Add a seperate tag, filter just modsec audit logs based on regex and stream to another Opensearch
- Filter the ingress logs to pattern match specific strings which are in modsec audit log using lua script and redact it

Modsec audit data redacting and multiple output streams

---

main.tf

This PR increase a wait timeout which allows the fluent-bit chart to apply on clusters which has lot of nodes e.g. live.

Increase timout for fluent-bit chart for long wait

---

templates/fluent-bit.yaml.tpl

- Use lua and regex to match the github_team name
- Add a new record to the modsec logs with this extracted team name
This enables opensearch to restrict access based on this value to users who are in those teams
Part of [#4504](https://github.com/ministryofjustice/cloud-platform/issues/4504)

feat: 🎸 tag modsec logs with github team

---

templates/fluent-bit.yaml.tpl

Lua wasn't tagging logs because Keep_Log had been switched off and move the filter to run after the kubernetes filter has ran

fix: 🐛 switch Keep_Log On and move lua filter to last

---

README.md
examples/logging.tf
main.tf
templates/fluent-bit.yaml.tpl
variables.tf

This is no longer used, and the last log we hold in ElasticSearch from this integration is from April 2022.

Remove integration for pushing `kube-apiserver-audit` logs into ElasticSearch, as these are now stored in CloudWatch

---

templates/fluent-bit.yaml.tpl

- Breaching the memory buffer limit caused fluent bit to stop tailing from the source. We have raised the in memory chunk limit to 500 (chunks being a maximum of 2mb) and we are writing logs which breach this limit to the filesystem, so we can pick these up when memory frees up. [This means we no longer drop logs (we get increased data safety) and the performance of storing in memory](https://docs.fluentbit.io/manual/administration/buffering-and-storage#filesystem-buffering-to-the-rescue).
- Introduced a sqlite db to capture where in the log file we pause the tailing so when tailing resumes it can resume from where we left off.
- Fixed a bug where pod lookups were failing with a 404 from the kube API, this was because we were removing the part of the pod name before lookup.
[drastically …

Hotfix mem buf limit err

---

templates/fluent-bit.yaml.tpl

- reduce `Storage.max_chunks_up` so we can flush the chunks to es quicker
- add `Multiline.parser` as recommended, so we can output multi-line logs from docker as one log
- Add `Grace` to allow chunks to flush on pod shutdown

perf: ⚡️ flush logs more frequently in smaller chunks

---

templates/fluent-bit.yaml.tpl

We should match alphanumeric characters and not just letters (integration tests mock github_team uses alphanumeric characters)
https://www.lua.org/pil/20.2.html

style: 💄 regex alphanumeric for int tests

---

main.tf

This PR increases the memory limit of the container thereby avoiding fluenbit pod to get OOMKilled. 
https://mojdt.slack.com/archives/C8QR5FQRX/p1696347216264199

Bump memory limit to fix OOMKilled of fluent-bit pod

---

README.md
templates/fluent-bit.yaml.tpl

fluent bit was having issues dropping modsec logs when there were 2 opensearch outputs defined, move modsec log closer to modsec and with other aspects of modsec logging by the ingress controllers
and push user app logs to our new open search cluster

perf: ⚡️ remove modsec opensearch & add user app opensearch

---

templates/fluent-bit.yaml.tpl

fluent-bit crashlooping debugging 1: disable luascript team vals config, we are seeing errors in live logs:
`[2024/05/13 10:43:32] [error] [filter:lua:user_app_data_os] error code 2: /fluent-bit/scripts/cb_extract_team_values.lua:2: attempt to index field 'annotations' (a nil value)`

Remove lua

---

main.tf

since upgrading to 3.0.2 we are seeing freqeunt crashloops. roll back for stability until 3 issues resolved

fix: 🐛 rollback fluentbit to 2.2.1

---

templates/fluent-bit.yaml.tpl

- tag each log by reading the `github_teams` annotation and reformatting it
- if annotation doesn't exist apply default `all-org-members`

fix: 🐛 revert lua and add default value github_teams anno

---

templates/fluent-bit.yaml.tpl

- Reverts disabling opensearch in fluent-bit
- Re-added output sections to fluent-bit conf
-This reverts commit 7242a59a8fbb05903915a6eb59ee48f71cb1296e.

Revert "chore: 🤖 temp disabling of opensearch output, filter and lua"

---

templates/fluent-bit.yaml.tpl

- event router is only output to std (missed turning back on post incident)

fix: 🐛 eventrouter to os

---

templates/fluent-bit.yaml.tpl

- it's difficult to test the time index changes, let's trail it on a less important index and roll out if successful

fix: 🐛 index date

---

templates/fluent-bit.yaml.tpl

- I have tested on ipamd and the index is created properly with this flag on, trial this method (current time on the server) of created the date for the index instead of reading it from the log
https://docs.fluentbit.io/manual/pipeline/outputs/opensearch

fix: 🐛 use Current_Time_Index

---

main.tf

- tested on a test cluster, upgrade went smoothly (be prepared to roll back in live though as this is a major version change that failed previously app version 2.2.1 -> 3.2.8)

chore: 🤖 0.42.0 -> 0.48.9 helm chart bump

---

main.tf
templates/fluent-bit.yaml.tpl

- add back kubernetes_events
- add isolated threads for write heavy indexes https://docs.fluentbit.io/manual/administration/multithreading

Debug timestamp logs 2

---

templates/fluent-bit.yaml.tpl

- we are shipping modsec controller access logs to opensearch app logs from the ingress controller flb now. We don't need to also tail them here
- generic-json isn't parsing the log as it isn't json

fix: 🐛 exclude modsec access logs

---

templates/fluent-bit.yaml.tpl

- make tail path pattern more specific, logs are being sent to ingress index when they are just any old nginx container
- remove unused pattern matched (modsec logs are handled at the modsec nginx ingress level)

fix: 🐛 ingress index pattern too broad

---

templates/fluent-bit.yaml.tpl

- I removed this last week because modsec ingress logs aren't json, however default ingress logs are and we have now separated the 2 so revert this change

fix: 🐛 ingress controller logs real json

---

templates/fluent-bit.yaml.tpl

- still seeing the occasional bug where logs keep flowing after namespace is gone
- push smaller chunks to opensearch (will increase os throughput so watch for too many retries and 429s)

perf: ⚡️ reduce chunk size and increase rotate wait

---

main.tf

## Purpose
Increase hard pod limit to resolve LPA alerts:
```
warning: KubeQuota-Exceeded
Alert: Namespace logging is using 91% of its pods quota.
```

chore: 🤖 increase pod hard limit for daemonset
